needs to handle when params are 1 char

diff --git a/lab3/reextend b/lab3/reextend
--- a/lab3/reextend
+++ b/lab3/reextend
@@ -4,29 +4,45 @@ usage() {
 	echo "Usage: reextend oldExt newExt"
 }
 
-if [ $# -ne 2 ] ;
+if [ $# -lt 2 ] ; # Error handle not getting enough arguments
 then
 	echo "ERROR: Not enough arguments" ; usage ; exit
+elif [ $# -gt 2 ] ; # Error handle getting too many arguments
+then
+	echo "ERROR: Too many argument" ; usage ; exit
 fi
 
+echo param1: $1
+echo param2: $2
+
+# Total items counted
 itemsFound=0
 
-ls | while read item ; do
-	if [ "$item" = *$1 ] ; then
-		c_old=${#1}
-		c_name=${#item}
-		let "c_diff= $c_name - $c_old"
+# Iterate over each item from ls call
+while read item ; do
+	echo $item
+	# If the file extension matches the second command line argument
+	if [ "$item" = *"$1" ] ; then
+		# Increment the item counter
+		itemsFound=$((itemsFound+1))
+		# Calculate the length of filename without the old extension
+		let "c_diff= ${#item} - ${#1}"
+		# Rename the file to the new extension
 		mv "$item" ${item:0:c_diff}$2
-		echo $item was renamed to ${item:0:c_diff}$2
+		if [ $? -ne 0 ] ; then
+			echo "ERROR: mv command failed renaming $item" ; exit
+		fi
+		echo file $item was renamed to ${item:0:c_diff}$2
 	fi
-done
+done <<<$(ls) # This syntax to run while loop within same shell as main program so global variables can be edited
 
-echo $itemsFound
-
+# On the case of no items were found
 if (( $itemsFound == 0 )) ; then
 	echo "ERROR: No items found with extension $1"
 	exit
 else 
+	# Output number of files successfuly operated on
 	echo "Successfully renamed $itemsFound files"
+	exit
 fi
 
